resources:
- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git
    branch: master
- name: cf-smoke-tests-concourse
  type: git
  source:
    uri: https://github.com/jacek-rzrz/cf-smoke-tests-concourse.git
    branch: master
jobs:
- name: run-smoke-tests
  plan:
  - get: cf-smoke-tests
  - get: cf-smoke-tests-concourse
  - task: run-smoke-tests
    file: cf-smoke-tests-concourse/tasks/run-smoke-tests.yml
