resources:
- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git
    branch: master
- name: cf-smoke-tests-concourse
  type: git
  source:
    uri: https://github.com/jacek-rzrz/cf-smoke-tests-concourse.git
    branch: master
- name: cf-smoke-tests-config
  type: s3
  source:
    bucket: cf-smoke-tests-concourse
    regexp: integration_config-(.*).json
    access_key_id: {{access_key_id}}
    secret_access_key: {{secret_access_key}}
jobs:
- name: run-smoke-tests
  plan:
  - get: cf-smoke-tests
  - get: cf-smoke-tests-concourse
  - get: cf-smoke-tests-config
  - task: run-smoke-tests
    file: cf-smoke-tests-concourse/tasks/run-smoke-tests.yml
